import sqlite3

# Создание базы данных и таблицы
conn = sqlite3.connect("data_base_of_movies.db")
cursor = conn.cursor()

cursor.execute("""
CREATE TABLE IF NOT EXISTS movies (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    title_en TEXT,
    description_en TEXT,
    title_ru TEXT,
    description_ru TEXT,
    title_ua TEXT,
    description_ua TEXT,
    title_cz TEXT,
    description_cz TEXT,
    url TEXT,
    genres TEXT,
    length_of_film INTEGER,
    netflix_url TEXT
)
""")

# Примерные 10 фильмов. Позже можно расширить до 100.
sample_movies = [
        (
        "The Social Network (2010)",
        "The founding of Facebook leads to lawsuits, betrayal and intense rivalry among its creators.",
        "Социальная сеть (2010)",
        "Создатели Facebook спорят и судятся из-за власти и долей.",
        "Соціальна мережа (2010)",
        "Розробка Facebook стає причиною конфліктів та судових позовів.",
        "Síť (2010)",
        "Rozvoj Facebooku způsobí napětí mezi zakladateli.",
        "https://www.youtube.com/watch?v=lB95KLmpLR4",
        "Drama,Detective,Biography",
        2,
        "https://www.netflix.com/title/70132603"
    ),
    (
        "A Beautiful Mind (2001)",
        "A brilliant but asocial mathematician fights schizophrenia while making groundbreaking contributions.",
        "Игры разума (2001)",
        "Математик борется с галлюцинациями, спасая свою карьеру и семью.",
        "Ігри розуму (2001)",
        "Вчений веде внутрішню війну з шизофренією.",
        "Čistý rozum (2001)",
        "Matematik bojuje s psychickými démony, ale mění svět.",
        "https://www.youtube.com/watch?v=YWwAOutgWBQ",
        "Drama,Biography",
        3,
        "https://www.netflix.com/title/60000342"
    ),
    (
        "Lion (2016)",
        "A lost Indian boy, adopted by an Australian couple, searches for his lost family.",
        "Лев (2016)",
        "Похожий на эмиграцию путь юного героя к своим корням.",
        "Лев (2016)",
        "Хлопець шукає рідних після усиновлення за кордоном.",
        "Lví král (2016)",
        "Ztracený chlapec hledá svou skutečnou rodinu.",
        "https://www.youtube.com/watch?v=YF6rBDyr8-g",
        "Drama,Adventure",
        2,
        "https://www.netflix.com/title/80104637"
    ),
    (
        "Spotlight (2015)",
        "Journalists expose long-hidden abuses in the highest ranks of the Church hierarchy.",
        "В центре внимания (2015)",
        "Журналисты раскрывают правду, несмотря на сопротивление.",
        "У центрі уваги (2015)",
        "Журналісти викривають корупцію й складні замовлення.",
        "Ve stínu (2015)",
        "Novináři bojují s institucí ve jménu pravdy.",
        "https://www.youtube.com/watch?v=MBsYqlOqe9k",
        "Drama,Detective,Biography",
        2,
        "https://www.netflix.com/title/80014218"
    ),
    (
        "Baby Driver (2017)",
        "A young getaway driver uses music to stay focused during high-speed bank heists.",
        "Беби драйвер (2017)",
        "Молодой водитель участвует в погонях, слушая плейлист на полной скорости.",
        "Бебі драйвер (2017)",
        "Під час погонь герой слухає музику, що його рятує.",
        "Baby Driver (2017)",
        "Mladý řidič uniku používá hudbu jako tempo.",
        "https://www.youtube.com/watch?v=Z9AYPxH5NTM",
        "Action,Crime",
        2,
        "https://www.netflix.com/title/80109262"
    ),
    (
        "Once Upon a Time in Hollywood (2019)",
        "An actor and his stunt double strive for fame in 1960s Los Angeles.",
        "Однажды в Голливуде (2019)",
        "Режиссёр, актёр и дублёр ищут место в меняющемся кинематографе.",
        "Одного разу в Голлівуді (2019)",
        "Герої переживають зміну епох у світі кіно.",
        "Tenkrát v Hollywoodu (2019)",
        "Herec a dublér hledají slávu v burácícím Hollywoodu.",
        "https://www.youtube.com/watch?v=Q8QXtEo4WLI",
        "Drama,Comedy",
        3,
        "https://www.netflix.com/title/81101801"
    ),
    (
        "Her (2013)",
        "A lonely writer develops intimacy with an advanced AI operating system.",
        "Она (2013)",
        "Человек влюбляется в виртуальную сущность.",
        "Вона (2013)",
        "Любовь между человеком и программой.",
        "Ona (2013)",
        "Osamělý muž naváže citový vztah s AI.",
        "https://www.youtube.com/watch?v=WzV6mXIOVl4",
        "Sci‑fi,Drama,Romance",
        2,
        "https://www.netflix.com/title/70278988"
    ),
    (
        "Parasite (2019)",
        "A poor family schemes to infiltrate a wealthy household with unexpected consequences.",
        "Паразиты (2019)",
        "Социальная трагедия с острым оттенком сатиры.",
        "Паразити (2019)",
        "Соціальна сатира через контрасти класів.",
        "Parazit (2019)",
        "Chudá rodina infiltruje bohatou rodinu.",
        "https://www.youtube.com/watch?v=SEUXfv87Wpk",
        "Drama,Thriller,Crime",
        2,
        "https://www.netflix.com/title/81005150"
    ),
    (
        "Trainspotting (1996)",
        "A group of heroin addicts navigate love, sorrow, and survival in Edinburgh.",
        "На западе (1996)",
        "Подростки и взрослые в ловушке наркотиков и выбора.",
        "На Захиді (1996)",
        "Герої – жертви залежності у повсякденному житті.",
        "Trainspotting (1996)",
        "Skupina závislých bojuje s realitou a зависимостьí.",
        "https://www.youtube.com/watch?v=8UVNT4wvIGY",
        "Drama,Crime",
        2,
        "https://www.netflix.com/title/60031256"
    ),
    (
        "The Pianist (2002)",
        "A Polish Jewish musician struggles to survive the destruction of the Warsaw ghetto.",
        "Пианист (2002)",
        "История выживания мужчины в годы Холокоста.",
        "Піаніст (2002)",
        "Виживання в гетто через музику і человеческую стойкость.",
        "Pianista (2002)",
        "Polský hudebník přežije holocaust díky své hudbě.",
        "https://www.youtube.com/watch?v=BFwGqLa_oAo",
        "Drama,Biography,Historical,Military",
        3,
        "https://www.netflix.com/title/60025063"
    ),
    (
        "Lady Bird (2017)",
        "A teenager navigates family tension and personal ambition in her final year of high school.",
        "Леди Бёрд (2017)",
        "Подростковая драма о взрослении и поиске себя.",
        "Леді Берд (2017)",
        "Дівчина шукає себе між дитиною та дорослістю.",
        "Lady Bird (2017)",
        "Teenager hledá vlastní cestu mezi školou a домом.",
        "https://www.youtube.com/watch?v=cNi_HC839Wo",
        "Drama,Melodrama",
        2,
        "https://www.netflix.com/title/80178017"
    ),
    (
        "Call Me by Your Name (2017)",
        "In Italy in 1983, a romance blossoms between a teenager and an older visiting scholar.",
        "Назови меня своим именем (2017)",
        "История нежной любви в летней Италии.",
        "Назви мене своїм іменем (2017)",
        "Любовь, рожденная в путешествии и вдохновении.",
        "Prokletý ostrov (2017)",
        "Romantika mezi dvěma rozdílnými světy ve 80. letech.",
        "https://www.youtube.com/watch?v=Z9AYPxH5NTM",
        "Melodrama,Drama",
        2,
        "https://www.netflix.com/title/80236331"
    ),
    (
        "Invictus (2009)",
        "Nelson Mandela uses the national rugby team to unite post‑apartheid South Africa.",
        "Непокорённый (2009)",
        "Спорт как инструмент национального примирения.",
        "Непокорений (2009)",
        "Спорт об’єднав країну в нових реаліях.",
        "Nelsonův soupeř (2009)",
        "Sport sjednocuje národ po apartheidu.",
        "https://www.youtube.com/watch?v=XYxarHRX0t4",
        "Sports,Drama,Biography",
        2,
        "https://www.netflix.com/title/60021578"
    ),
    (
        "Slumdog Millionaire (2008)",
        "A Mumbai teen accused of cheating on a game show tells his life story to prove innocence.",
        "Миллионер из трущоб (2008)",
        "История выживания и любви среди нищеты.",
        "Мільйонер із нетрів (2008)",
        "Життя Германа – драматичне і вдохновляющее.",
        "Slumdog Millionaire (2008)",
        "Chudý chlapec z města přežívá a vychází do světa.",
        "https://www.youtube.com/watch?v=AIzbwV7on6Q",
        "Drama,Romance",
        2,
        "https://www.netflix.com/title/70058583"
    ),
    (
        "Stand by Me (1986)",
        "Four boys go on a hike to find a missing boy’s body and discover themselves in the process.",
        "Останься со мной (1986)",
        "Детство, дружба и взросление на пороге перемен.",
        "Залишайся зі мною (1986)",
        "Дружба, приключения и прощание с детством.",
        "Stůj při mně (1986)",
        "Cesta za hranицей dětství a незабываемые уроки.",
        "https://www.youtube.com/watch?v=RZzWpuPIK4t",
        "Adventure,Drama",
        1,
        "https://www.netflix.com/title/60001914"
    ),
    (
        "The Farewell (2019)",
        "A family decides not to tell their matriarch about her terminal cancer diagnosis and gathers before her death.",
        "Прощание (2019)",
        "История любви, потери и культурных различий в семье.",
        "Прощання (2019)",
        "Родина ховає правду заради материнського душевного спокою.",
        "Rozloučení (2019)",
        "Rodina schovává nemoc, aby zachovala naději.",
        "https://www.youtube.com/watch?v=Q9aPx7fYQnQ",
        "Drama,Family",
        2,
        "https://www.netflix.com/title/81135800"
    ),
        (
        "A Separation (2011)",
        "A married couple faces a moral crisis over whether to leave Iran for medical treatment or stay with their senile father.",
        "Развод (2011)",
        "Пара сталкивается с трудным выбором: уехать из страны или остаться ради больного отца.",
        "Розлучення (2011)",
        "Пара повинна вирішити: порятунок здоров’я чи відданість родині.",
        "Rozchod (2011)",
        "Manželé čelí dilema mezi léčbou v cizině a opravou rodinných vztahů.",
        "https://www.youtube.com/watch?v=5KKQlQjn_xc",
        "Drama,Detective",
        2,
        "https://www.netflix.com/title/70234320"
    ),
    (
        "The Big Short (2015)",
        "Investors foresee the 2008 financial collapse and bet against the housing market.",
        "Игра на понижение (2015)",
        "Группа экономистов предсказывает кризис и делает на нем состояние.",
        "Великий короткий (2015)",
        "Аналітики передбачають фінансовий крах і заробляють на ньому.",
        "Velká hra (2015)",
        "Skupina analytiků vsází proti trhu před krizí.",
        "https://www.youtube.com/watch?v=vgqG3ITMv1Q",
        "Drama,Crime,Comedy",
        2,
        "https://www.netflix.com/title/80074808"
    ),
    (
        "Room (2015)",
        "A woman held captive for years finally escapes with her young son.",
        "Комната (2015)",
        "Мать и ребёнок освобождаются после длительного заточения.",
        "Кімната (2015)",
        "Мати і син звільняються після років ув’язнення.",
        "Room (2015)",
        "Žena a syn konečně získají svobodu po letech v zajetí.",
        "https://www.youtube.com/watch?v=E_Ci-pAL4eE",
        "Drama,Thriller",
        2,
        "https://www.netflix.com/title/80079283"
    ),
    (
        "Manchester by the Sea (2016)",
        "A grieving janitor returns to his hometown to take care of his teenage nephew.",
        "Манчестер у море (2016)",
        "Убитый горем мужчина возвращается домой после смерти брата.",
        "Менчестер біля моря (2016)",
        "Чоловік повертається доглядати єдиного родича.",
        "Manchester u moře (2016)",
        "Žena vrací do rodného města poté, co ztratí bratra.",
        "https://www.youtube.com/watch?v=YxCMPhoC0eA",
        "Drama",
        2,
        "https://www.netflix.com/title/80177210"
    ),
    (
        "Spotlight (2015)",
        "Investigative journalists expose child abuse in the Church.",
        "В центре внимания (2015)",
        "Репортеры раскрывают мощный скандал.",
        "У центрі уваги (2015)",
        "Журналісти борються за правду.",
        "Ve stínu (2015)",
        "Novináři odhalují silný skandál.",
        "https://www.youtube.com/watch?v=MBsYqlOqe9k",
        "Drama,Detective,Biography",
        2,
        "https://www.netflix.com/title/80014218"
    ),
    (
        "Moonlight (2016)",
        "A young man grapples with identity, sexuality and family across three stages of his life.",
        "Лунный свет (2016)",
        "История взросления и самопознания.",
        "Місячне світло (2016)",
        "Зростання хлопця на фоні суспільних бар’єрів.",
        "Moonlight (2016)",
        "Mladík hledá své místo ve světě.",
        "https://www.youtube.com/watch?v=9NJj12tJzqc",
        "Drama",
        2,
        "https://www.netflix.com/title/80121348"
    ),
    (
        "Parasite (2019)",
        "A poor family schemes to become employed by a wealthy family and infiltrate their household.",
        "Паразиты (2019)",
        "Социальная подлость приводит к трагическим последствиям.",
        "Паразити (2019)",
        "Родина пробирається в заможний дім.",
        "Parazit (2019)",
        "Chudá rodina pronikne k bohatým.",
        "https://www.youtube.com/watch?v=SEUXfv87Wpk",
        "Drama,Thriller,Crime",
        2,
        "https://www.netflix.com/title/81005150"
    ),
    (
        "Shoplifters (2018)",
        "A poor family relies on shoplifting to cope with a life of poverty in Tokyo.",
        "Нелегкое счастье (2018)",
        "Сблизившиеся вынужденным выбором семья борется за выживание.",
        "Крадії (2018)",
        "Родина виживає викраденням дрібниць.",
        "Mahluk (2018)",
        "Chudá rodina přežívá drobnými krádežами.",
        "https://www.youtube.com/watch?v=ji5-MqicxSo",
        "Drama,Crime,Family",
        2,
        "https://www.netflix.com/title/80198579"
    ),
    (
        "Three Billboards Outside Ebbing, Missouri (2017)",
        "A mother challenges local authorities to solve her daughter's murder when they fail to catch the culprit.",
        "Три билборда на границе Эббинга (2017)",
        "Женщина борется за правду после трагедии.",
        "Три білборди (2017)",
        "Мати вимагає справедливості в селі.",
        "Tři billboardy (2017)",
        "Matka vzpouzí autority po vraždě dcery.",
        "https://www.youtube.com/watch?v=SQPsbV5u-b0",
        "Drama,Crime",
        2,
        "https://www.netflix.com/title/80143528"
    ),
    (
        "Arrival (2016)",
        "A linguist works to communicate with alien lifeforms after mysterious spacecraft land around the world.",
        "Прибытие (2016)",
        "Лингвист пытается предотвратить мировую войну.",
        "Прибуття (2016)",
        "Лінгвістка допомагає комунікувати з прибульцями.",
        "Příchozí (2016)",
        "Lingvistka navazuje kontakt mimozemšťany.",
        "https://www.youtube.com/watch?v=tFMo3UJ4B4g",
        "Sci-fi,Drama,Detective",
        2,
        "https://www.netflix.com/title/80121347"
    ),
    (
        "1917 (2019)",
        "Two soldiers are tasked with delivering a message deep in enemy territory in WWI.",
        "1917 (2019)",
        "Война в одном кадре: миссия с риском для жизни.",
        "1917 (2019)",
        "Двоє солдатів виконують смертельне завдання.",
        "1917 (2019)",
        "Dva vojáci dostanou úkol doručit zprávu za nepřátelské linie.",
        "https://www.youtube.com/watch?v=YqNYrYUiMfg",
        "War,Drama,Adventure",
        2,
        "https://www.netflix.com/title/81150714"
    ),
    (
        "Lady Bird (2017)",
        "A teenager navigates a complicated relationship with her mother while planning for college.",
        "Леди Бёрд (2017)",
        "Юность, взросление и конфликт поколений.",
        "Леді Берд (2017)",
        "Підліткова драма про вибір і свободу.",
        "Lady Bird (2017)",
        "Nastolatka hledá svou cestu mezi láskou, školou a домом.",
        "https://www.youtube.com/watch?v=cNi_HC839Wo",
        "Drama,Melodrama",
        2,
        "https://www.netflix.com/title/80178017"
    ),
    (
        "Get Out (2017)",
        "A young African-American visits his girlfriend’s parents and uncovers disturbing secrets.",
        "Прочь (2017)",
        "Жена не та, кем кажется — приём у родителей превращается в кошмар.",
        "Геть (2017)",
        "Сімейний візит обертається кошмаром.",
        "Uteč (2017)",
        "Mladý muž odhalí zlověstné tajemství rodiny.",
        "https://www.youtube.com/watch?v=DzfpyUB60YY",
        "Horror,Thriller,Drama",
        2,
        "https://www.netflix.com/title/80108975"
    ),
    (
        "Green Book (2018)",
        "An African-American pianist and his driver embark on a tour of the racially segregated South.",
        "Зелёная книга (2018)",
        "Дружба на фоне расовых предрассудков США.",
        "Зелена книга (2018)",
        "Диялог дружби і расових бар'єрів.",
        "Zelená kniha (2018)",
        "Hudebník a řidič čelí segregaci na jihu USA.",
        "https://www.youtube.com/watch?v=XpVfcZ0ZcFM",
        "Drama,Biography",
        2,
        "https://www.netflix.com/title/80200638"
    ),
    (
        "Portrait of a Lady on Fire (2019)",
        "In 18th‑century France, a forbidden affair blooms between an aristocrat and a painter.",
        "Портрет девушки в огне (2019)",
        "Страсть и искусство на фоне феминистской Франции.",
        "Портрет дівчини у вогні (2019)",
        "Кохання, яке не могло быть публичным.",
        "Portrét dívky v plamenech (2019)",
        "Zákazané cítění mezi aristokratkou a malířkou.",
        "https://www.youtube.com/watch?v=H3Bat9H3kei",
        "Drama,Romance",
        1,
        "https://www.netflix.com/title/81253952"
    ),
        (
        "Children of Heaven (1997)",
        "A brother risks punishment to share a pair of lost shoes with his sister.",
        "Дети небес (1997)",
        "Брат и сестра делят одну пару обуви после потери второй.",
        "Діти небес (1997)",
        "Брат і сестра мають одну пару взуття після втрати другої.",
        "Děti nebe (1997)",
        "Sourozenci sdílí jednu botu po ztrátě druhé.",
        "https://www.youtube.com/watch?v=ua7K9tvOElc",
        "Family,Drama",
        1,
        "https://www.netflix.com/title/60033811"
    ),
    (
        "Gran Torino (2008)",
        "A grumpy veteran bonds with a neighbor boy as he struggles with his own biases.",
        "Гран Торино (2008)",
        "Ветеран войны меняет жизнь подростка и свою собственную.",
        "Гран Торіно (2008)",
        "Ветеран допомагає молодому сусідові і змінюється сам.",
        "Gran Torino (2008)",
        "Stárnoucí veterán pomáhá svému sousedovi a nachází smíření.",
        "https://www.youtube.com/watch?v=RMhbr2XQblk",
        "Drama,Crime",
        2,
        "https://www.netflix.com/title/60012077"
    ),
    (
        "The Shape of Water (2017)",
        "A mute janitor forms a bond with an amphibious creature in a secret lab.",
        "Форма воды (2017)",
        "Молчаливая уборщица вступает в необычные отношения с чудовищем.",
        "Форма води (2017)",
        "Німість прибиральниці веде до несподіваного зв’язку з істотою.",
        "Tvar vody (2017)",
        "Tichá uklízečka naváže pouto s podivnou bytostí.",
        "https://www.youtube.com/watch?v=XFYWazblaUA",
        "Fantasy,Romance,Drama",
        2,
        "https://www.netflix.com/title/80141450"
    ),
    (
        "Mad Max: Fury Road (2015)",
        "In a post-apocalyptic wasteland, Max teams with Furiosa to flee a tyrannical warlord.",
        "Безумный Макс: Дорога ярости (2015)",
        "Макс и Фуриоза бегут через пустоши, преследуемые диктатором.",
        "Божевільний Макс: Дорога люті (2015)",
        "Макс і Фуріоза рятуються від диктатора у пустелі.",
        "Šílený Max: Zběsilá cesta (2015)",
        "Max a Furiosa unikají tyranskému vládci v pustině.",
        "https://www.youtube.com/watch?v=hEJnMQG9ev8",
        "Action,Adventure,Drama",
        2,
        "https://www.netflix.com/title/80057159"
    ),
    (
        "Spotlight (2015)",
        "Boston Globe reporters expose a massive child abuse scandal in the Catholic Church.",
        "В центре внимания (2015)",
        "Журналисты раскрывают масштабный скандал в католической церкви.",
        "У центрі уваги (2015)",
        "Журналісти викривають системне насильство в церкві.",
        "Ve stínu (2015)",
        "Novináři odhalili skandál, který otřásl institucí.",
        "https://www.youtube.com/watch?v=MBsYqlOqe9k",
        "Drama,Detective,Biography",
        2,
        "https://www.netflix.com/title/80014218"
    ),
    (
        "The Departed (2006)",
        "An undercover cop and a mole in the police play a deadly game in Boston gangs.",
        "Отступники (2006)",
        "Полицейский и мафиози — каждый находится в стане другого.",
        "Підсадний шахрай (2006)",
        "Агент і кріт переглядають ролі один одного у грі.",
        "Skrytý nepřítel (2006)",
        "Policista a infiltrátor hrají smrtelnou hru v Bostonu.",
        "https://www.youtube.com/watch?v=iojhqm0JTW4",
        "Crime,Drama,Thriller",
        3,
        "https://www.netflix.com/title/70097009"
    ),
    (
        "The Martian (2015)",
        "An astronaut stranded on Mars must use his ingenuity to signal Earth that he's alive.",
        "Марсианин (2015)",
        "Астронавт борется за выживание на Марсе после аварии.",
        "Марсіянин (2015)",
        "Астронавт залишається один на Марсі і бореться за врятування.",
        "Marťan (2015)",
        "Astronaut na Marsu bojuje o život a kontakt s domovem.",
        "https://www.youtube.com/watch?v=ej3ioOneTy8",
        "Sci-fi,Adventure,Drama",
        2,
        "https://www.netflix.com/title/80133331"
    ),
    (
        "Life of Pi (2012)",
        "After a shipwreck, a young man survives in a lifeboat with a Bengal tiger.",
        "Жизнь Пи (2012)",
        "Хлопец выживает после крушения и плавает с тигром.",
        "Життя Пі (2012)",
        "Після аварії хлопець вижив у човні з тигром.",
        "Pí a jeho život (2012)",
        "Mladík přežije mořskou katastrofu se tygrem.",
        "https://www.youtube.com/watch?v=jY9h38lX3tY",
        "Adventure,Drama",
        3,
        "https://www.netflix.com/title/70283253"
    ),
    (
        "Dead Poets Society (1989)",
        "A teacher inspires students through poetry to seize the day.",
        "Общество мёртвых поэтов (1989)",
        "Учитель мотивирует учеников жить полной жизнью.",
        "Товариство мертвих поетів (1989)",
        "Викладач надихає студентів до сміливості.",
        "Společnost mrtvých básníků (1989)",
        "Učitel povzbuzuje studenty skrze poezii.",
        "https://www.youtube.com/watch?v=wrKi4EZ1mgA",
        "Drama,Family",
        2,
        "https://www.netflix.com/title/60000463"
    ),
    (
        "The Hunt (2012)",
        "A man’s life unravels after a false accusation of child abuse.",
        "Охота (2012)",
        "Мужчину подозревают в преступлении, которого он не совершал.",
        "Полювання (2012)",
        "Чоловіка безпідставно звинувачують, і його життя рушиться.",
        "Hon (2012)",
        "Muž je neprávem obviněn a jeho život se rozpadá.",
        "https://www.youtube.com/watch?v=2YlR0fE0X0Y",
        "Drama,Crime",
        2,
        "https://www.netflix.com/title/70294815"
    ),
    (
        "Children of Heaven (1997)",
        "A brother and sister share a single pair of shoes after one is lost.",
        "Дети небес (1997)",
        "Юные брат и сестра делят одну пару обуви.",
        "Діти небес (1997)",
        "Брат і сестра мають одну пару взуття після втрати.",
        "Děti nebe (1997)",
        "Sourozenci sdílí jednu botu po ztrátě druhé.",
        "https://www.youtube.com/watch?v=ua7K9tvOElc",
        "Family,Drama",
        1,
        "https://www.netflix.com/title/60033811"
    ),
    (
        "Moon (2009)",
        "An astronaut nearing the end of his lunar mission begins to doubt who he is.",
        "Луна (2009)",
        "Одинокий космонавт сталкивается с экзистенциальным кризисом.",
        "Місяць (2009)",
        "Астронавт на Місяці сумнівається у власній реальності.",
        "Měsíc (2009)",
        "Astronaut na Měsíci čelí existenční krizi.",
        "https://www.youtube.com/watch?v=SwSlSiJJQXI",
        "Sci-fi,Drama",
        2,
        "https://www.netflix.com/title/70264888"
    ),
    (
        "Black Swan (2010)",
        "A committed ballerina descends into madness while preparing for the lead role.",
        "Чёрный лебедь (2010)",
        "Балерина теряет себя под давлением идеала.",
        "Чорний лебідь (2010)",
        "Балерина переживає крах через вимоги до досконалості.",
        "Černý labuť (2010)",
        "Baletka propadá pod tlakem vlastní posedlosti.",
        "https://www.youtube.com/watch?v=5jaI1XOB-bs",
        "Drama,Thriller",
        2,
        "https://www.netflix.com/title/70258827"
    ),
    (
        "The Truman Show (1998)",
        "An insurance salesman realizes his life is a televised show after discovering bizarre facts.",
        "Шоу Трумана (1998)",
        "Человек выходит из иллюзии своей жизни и открывает правду.",
        "Шоу Трумана (1998)",
        "Чоловік відкриває, що все його життя — шоу.",
        "Truman Show (1998)",
        "Muž zjistí, že celý jeho život je sledován.",
        "https://www.youtube.com/watch?v=2SvWeLwfZZY",
        "Drama,Fantasy",
        2,
        "https://www.netflix.com/title/60011620"
    ),
    (
        "Inglourious Basterds (2009)",
        "A group of Jewish-American soldiers plot to assassinate Nazi leaders in France.",
        "Бесславные ублюдки (2009)",
        "Солдаты разрабатывают операцию против нацистов во время Второй мировой.",
        "Безславні виродки (2009)",
        "Юдейські солдати планують вбивство нацистів під час війни.",
        "Hanební parchanti (2009)",
        "Partyzáni plánují zastavení nacistického režimu.",
        "https://www.youtube.com/watch?v=KnrRy6kSFF0",
        "Action,War,Drama",
        3,
        "https://www.netflix.com/title/70143836"
    ),
    (
        "Brooklyn (2015)",
        "An Irish immigrant lands in 1950s Brooklyn and faces difficult choices between two worlds.",
        "Бруклин (2015)",
        "Молодая иммигрантка ищет место между прошлым и настоящим.",
        "Бруклін (2015)",
        "Іммігрантка шукає баланс між новим життям і рідною землею.",
        "Brooklyn (2015)",
        "Iranka hledá štěstí ve světě plném možností.",
        "https://www.youtube.com/watch?v=H3MPgZEhaho",
        "Drama,Romance",
        2,
        "https://www.netflix.com/title/80024392"
    ),
    (
        "The Last Samurai (2003)",
        "An American military advisor embraces the samurai lifestyle he was hired to destroy.",
        "Последний самурай (2003)",
        "Американец обретает честь и жизнь среди самураев.",
        "Останній самурай (2003)",
        "Американець приймає культуру самураїв і змінюється.",
        "Poslední samuraj (2003)",
        "Americký muž hledá vykoupení mezi samurajskou cti.",
        "https://www.youtube.com/watch?v=yUjNXjuyYfo",
        "Action,Drama,Adventure",
        3,
        "https://www.netflix.com/title/60018001"
    ),
    (
        "Whiplash (2014)",
        "A driven drummer enrolls at an intense music conservatory under a demanding instructor.",
        "Одержимость (2014)",
        "Стремящаяся к совершенству барабанщица терпит давление учителя.",
        "Одержимість (2014)",
        "Музикантка змагається за визнання під тиском.",
        "Whiplash (2014)",
        "Talentovaný bubeník čelí extrémnímu tlaku učitele.",
        "https://www.youtube.com/watch?v=7d_jQycdQGo",
        "Drama,Musical",
        2,
        "https://www.netflix.com/title/70295172"
    ),
       (
        "Spotlight (2015)",
        "Investigative journalists uncover a widespread scandal of sexual abuse within the Catholic Church.",
        "В центре внимания (2015)",
        "Журналисты Boston Globe раскрывают масштабный скандал в католической церкви.",
        "У центрі уваги (2015)",
        "Журналісти розслідують системне насильство в церковній інституції.",
        "Ve stínu (2015)",
        "Novináři odhalují systematické zneužívání ve víře.",
        "https://www.youtube.com/watch?v=MBsYqlOqe9k",
        "Drama,Detective,Biography",
        2,
        "https://www.netflix.com/title/80014218"
    ),
    (
        "The Truman Show (1998)",
        "A man discovers that his entire life is a TV show broadcast to the world without his knowledge.",
        "Шоу Трумана (1998)",
        "Человек узнаёт, что вся его жизнь снимается и транслируется.",
        "Шоу Трумана (1998)",
        "Чоловік розуміє, що живе насправді на знімальному майданчику.",
        "Truman Show (1998)",
        "Muž zjistí, že celý jeho život sleduje milion diváků.",
        "https://www.youtube.com/watch?v=2SvWeLwfZZY",
        "Drama,Fantasy",
        2,
        "https://www.netflix.com/title/60011620"
    ),
    (
        "No Country for Old Men (2007)",
        "Violence and moral decay ensue after a hunter stumbles on drug money in the desert.",
        "Старикам тут не место (2007)",
        "После находки мешка с деньгами жизнь охотника превращается в кошмар.",
        "Старим тут не місце (2007)",
        "Мисливець натрапляє на наркотики, й його життя змінюється назавжди.",
        "No Country for Old Men (2007)",
        "Násilí a morální úpadek začínají po nálezu balíku peněz.",
        "https://www.youtube.com/watch?v=38A__WT3-o0",
        "Crime,Drama,Thriller",
        3,
        "https://www.netflix.com/title/70010831"
    ),
    (
        "District 9 (2009)",
        "An alien race is segregated in slums, until one man begins to transform irreversibly.",
        "Район №9 (2009)",
        "Пришельцы живут в гетто, пока один человек не меняется навсегда.",
        "Район №9 (2009)",
        "Інопланетяни живуть в таборах до початку нечуваних подій.",
        "District 9 (2009)",
        "Mimozemšťané jsou drženi v ghettu – jeden člověk to změní.",
        "https://www.youtube.com/watch?v=FhHRjrUJLdw",
        "Sci‑fi,Action,Drama",
        2,
        "https://www.netflix.com/title/70136117"
    ),
    (
        "The Wolf of Wall Street (2013)",
        "The rise and fall of Jordan Belfort as a stockbroker immersed in crime and excess.",
        "Волк с Уолл‑стрит (2013)",
        "Жадный брокер превращает свою жизнь в криминальную империю.",
        "Вовк з Уолл‑стріт (2013)",
        "Історія жадоби й падіння фінансового магната.",
        "Vlk z Wall Street (2013)",
        "Jordan Belfort dosáhne bohatství, ale vše ztratí kvůli chamtivosti.",
        "https://www.youtube.com/watch?v=iszwuX1AK6A",
        "Drama,Crime,Comedy",
        3,
        "https://www.netflix.com/title/70251562"
    ),
    (
        "Black Swan (2010)",
        "A ballerina descends into madness while competing for the lead role in Swan Lake.",
        "Чёрный лебедь (2010)",
        "Балерина погружается в саморазрушение в поисках идеального исполнения.",
        "Чорний лебідь (2010)",
        "Балерина переживає психологічний крах під час репетицій.",
        "Černý labuť (2010)",
        "Baletka upadá kvůli tlaku na dokonalost.",
        "https://www.youtube.com/watch?v=5jaI1XOB-bs",
        "Drama,Thriller",
        2,
        "https://www.netflix.com/title/70258827"
    ),
    (
        "Moon (2009)",
        "An astronaut nearing the end of his lunar mission begins to question his identity.",
        "Луна (2009)",
        "Одинокий космонавт начинает сомневаться в своей реальности.",
        "Місяць (2009)",
        "Астронавт на місяці бореться з ізоляцією та шоком.",
        "Měsíc (2009)",
        "Astronaut na Měsíci čelí existenční krizi.",
        "https://www.youtube.com/watch?v=SwSlSiJJQXI",
        "Sci‑fi,Drama",
        2,
        "https://www.netflix.com/title/70264888"
    ),
    (
        "Crouching Tiger, Hidden Dragon (2000)",
        "A warrior reclaims a stolen sword and faces forbidden love in the process.",
        "Крадущийся тигр, затаившийся дракон (2000)",
        "Воительница возвращает меч и обретает свободу.",
        "Тигр, що ховається, дракон (2000)",
        "Воїнка бореться за честь і любов.",
        "Tygr, který neslyší (2000)",
        "Bojovnice se vydává na cestu čestí a lásky.",
        "https://www.youtube.com/watch?v=UoV9Tx-5XKA",
        "Action,Fantasy,Drama",
        3,
        "https://www.netflix.com/title/60003998"
    ),
    (
        "The Intouchables (2011)",
        "After a paragliding accident leaves him quadriplegic, a wealthy man bonds with his caretaker.",
        "1+1 (2011)",
        "Аристократ с инвалидностью находит смысл жизни в дружбе.",
        "1+1 (2011)",
        "Багатий аристократ дружить із простим доглядальником.",
        "Nedotknutelní (2011)",
        "Bohatý aristokrat se učí žít znovu díky přátelství.",
        "https://www.youtube.com/watch?v=34WIbmXkewU",
        "Comedy,Drama",
        2,
        "https://www.netflix.com/title/70244571"
    ),
    (
        "Ford v Ferrari (2019)",
        "A legendary race car designer enlists a driver to challenge Ferrari at Le Mans.",
        "Форд против Феррари (2019)",
        "Автомобильная команда борется за победу в гонке века.",
        "Ford проти Ferrari (2019)",
        "Інженери створюють авто для змагань проти гіганта.",
        "Ford v Ferrari (2019)",
        "Americký designer a britský závodník bojují o titul.",
        "https://www.youtube.com/watch?v=zyY5s_LU8xw",
        "Biography,Drama,Sports",
        2,
        "https://www.netflix.com/title/80200926"
    ),
    (
        "Finding Nemo (2003)",
        "After his son is captured in the Great Barrier Reef, a clownfish embarks on a journey to rescue him.",
        "В поисках Немо (2003)",
        "Отец отправляется в океаническое приключение ради сына.",
        "У пошуках Немо (2003)",
        "Батько вирушає в подорож, щоб знайти сина.",
        "Hledá se Nemo (2003)",
        "Otec ryba pluje oceánem, aby zachránil syna.",
        "https://www.youtube.com/watch?v=wZdpNglLbt8",
        "Cartoon,Family",
        1,
        "https://www.netflix.com/title/60024977"
    ),
    (
        "The Last Samurai (2003)",
        "An American soldier embraces the Samurai code while living in Imperial Japan.",
        "Последний самурай (2003)",
        "Американец становится частью культуры, которую он должен был разрушить.",
        "Останній самурай (2003)",
        "Іноземець знаходить нову честь серед самураїв.",
        "Poslední samuraj (2003)",
        "Americký voják přechází na stranu samurajů proto, aby nalezl smysl.",
        "https://www.youtube.com/watch?v=yUjNXjuyYfo",
        "Action,Drama,Adventure",
        3,
        "https://www.netflix.com/title/60018001"
    ),
    (
        "Brooklyn (2015)",
        "An Irish immigrant adjusts to life in 1950s Brooklyn and is torn between two countries and two men.",
        "Бруклин (2015)",
        "Девушка пытается построить жизнь между домом и любовью.",
        "Бруклін (2015)",
        "Іммігрантка шукає баланс між новим домом і минулими коріннями.",
        "Brooklyn (2015)",
        "Iranka hledá štěstí v New Yorku 50. let.",
        "https://www.youtube.com/watch?v=H3MPgZEhaho",
        "Drama,Romance",
        2,
        "https://www.netflix.com/title/80024392"
    ),
    (
        "Dead Poets Society (1989)",
        "An English teacher inspires his students to seize the day through poetry.",
        "Общество мёртвых поэтов (1989)",
        "Учитель помогает ученикам жить полно и смело.",
        "Товариство мертвих поетів (1989)",
        "Викладач надихає студентів шукати сенс і свободу.",
        "Společnost mrtvých básníků (1989)",
        "Učitel motivuje mladé lidi k odvaze a svobodě.",
        "https://www.youtube.com/watch?v=wrKi4EZ1mgA",
        "Drama,Family",
        2,
        "https://www.netflix.com/title/60000463"
    ),
    (
        "Life of Pi (2012)",
        "After a shipwreck, a young man survives on a lifeboat with a Bengal tiger in the Pacific.",
        "Жизнь Пи (2012)",
        "Выживший после крушения молодой человек путешествует с тигром.",
        "Життя Пі (2012)",
        "Після аварії човна хлопець виживає разом із тигром у океані.",
        "Pí a jeho život (2012)",
        "Mladík přežije mořskou katastrofu v lodi s tygrem.",
        "https://www.youtube.com/watch?v=jY9h38lX3tY",
        "Adventure,Drama",
        3,
        "https://www.netflix.com/title/70283253"
    ),
    (
        "Mystic River (2003)",
        "Three childhood friends are torn apart by a tragic death and must confront their past.",
        "Таинственная река (2003)",
        "Трагедия возвращает друзей в детство, где прячется правда.",
        "Таємнича ріка (2003)",
        "Компанія друзів возз'єднується после довгої розлуки.",
        "Tajemná řeka (2003)",
        "Staré přátelství je testováno tragédií z minulosti.",
        "https://www.youtube.com/watch?v=HUECWi5pX7o",
        "Crime,Drama,Detective",
        3,
        "https://www.netflix.com/title/60005022"
    ),
    (
        "Inglourious Basterds (2009)",
        "A group of Jewish-American soldiers plan to assassinate Nazi leaders in occupied France.",
        "Бесславные ублюдки (2009)",
        "Солдаты готовят заговор против нацистов Франции.",
        "Безславні виродки (2009)",
        "Вояки-грантабри розробляють план помсти для нацистів.",
        "Hanební parchanti (2009)",
        "Partyzáni se pokoušejí zastavit nacistický režim.",
        "https://www.youtube.com/watch?v=KnrRy6kSFF0",
        "Action,War,Drama",
        3,
        "https://www.netflix.com/title/70143836"
    ),
    (
        "Inside Llewyn Davis (2013)",
        "A week in 1960s Greenwich Village, following a struggling folk singer navigating life and art.",
        "Внутри Льюина Дэвиса (2013)",
        "Музыкант живёт в мире неудач и мечтаний о славе.",
        "Внутрішній Льюїн Девіс (2013)",
        "Фольклорний виконавець шукає шлях до свого таланту.",
        "Inside Llewyn Davis (2013)",
        "Folkový zpěvák zmítaný osobní krizí v New Yorku.",
        "https://www.youtube.com/watch?v=mnG9L0ThKDo",
        "Drama,Musical",
        2,
        "https://www.netflix.com/title/80031629"
    ),
    (
        "Gran Torino (2008)",
        "An aging veteran forms an unlikely friendship with a young neighbor as he confronts his biases.",
        "Гран Торино (2008)",
        "Старый ветеран становится опорой для подростка, несмотря на предрассудки.",
        "Гран Торіно (2008)",
        "Ветеран війни знаходить сенс в дружбі з сусідським хлопцем.",
        "Gran Torino (2008)",
        "Starý veterán pomáhá mladému sousedovi a mění své názory.",
        "https://www.youtube.com/watch?v=RMhbr2XQblk",
        "Drama,Crime",
        2,
        "https://www.netflix.com/title/60012077"
    ),
        (
        "The Shape of Water (2017)",
        "At a Cold War–era research facility, a mute janitor forms a unique relationship with an amphibious creature being held in captivity.",
        "Лабиринт Фавы (2017)",
        "Молчаливая уборщица заводит связь с таинственным существом в секретной лаборатории.",
        "Форма води (2017)",
        "Німість черниці і незвичайна істота створюють зв’язок у секретній установі.",
        "Tvar vody (2017)",
        "Tichá uklízečka naváže pouto s podivnou bytostí v tajné laboratoři.",
        "https://www.youtube.com/watch?v=XFYWazblaUA",
        "Fantasy,Romance,Drama",
        2,
        "https://www.netflix.com/title/80141450"
    ),
    (
        "Spotlight (2015)",
        "True story of Boston Globe journalists uncovering widespread child abuse within the Catholic Church.",
        "В центре внимания (2015)",
        "Журналисты раскрывают масштабный скандал в католической церкви.",
        "У центрі уваги (2015)",
        "Журналісти розслідують системне насильство в церкві.",
        "Ve stínu (2015)",
        "Novináři odhalují škandál, který otřásl vírou.",
        "https://www.youtube.com/watch?v=MBsYqlOqe9k",
        "Drama,Detective,Biography",
        2,
        "https://www.netflix.com/title/80014218"
    ),
    (
        "The Departed (2006)",
        "An undercover cop and a mole in the police attempt to identify each other while infiltrating an Irish gang in Boston.",
        "Отступники (2006)",
        "Полицейский внедряется в мафию, мафиози внедряется в полицию — кто кого раскроет?",
        "Підсадний шахрай (2006)",
        "Агент і информатор пытаються разоблачить друг друга.",
        "Skrytý nepřítel (2006)",
        "Policista a mafián se vzájemně infiltruji.",
        "https://www.youtube.com/watch?v=iojhqm0JTW4",
        "Crime,Drama,Thriller",
        3,
        "https://www.netflix.com/title/70097009"
    ),
    (
        "The Aviator (2004)",
        "Biopic of Howard Hughes, focusing on his achievements in aviation and film production, and his struggles with mental illness.",
        "Авиатор (2004)",
        "История Говарда Хьюза: авиация, кино и психические сложности.",
        "Авіатор (2004)",
        "Життя і досягнення Генрі Г’юза, його боротьба з розумовими вадами.",
        "Aviátor (2004)",
        "Životní příběh Howarda Hughese jako průkopníka letectví.",
        "https://www.youtube.com/watch?v=hzcs7DXUKhc",
        "Biography,Drama,History",
        3,
        "https://www.netflix.com/title/60029917"
    ),
    (
        "Moon (2009)",
        "A solitary astronaut nearing the end of his three-year stint on the Moon begins to question his life and identity.",
        "Луна (2009)",
        "Одинокий астронавт задаётся вопросом: кто он на самом деле?",
        "Місяць (2009)",
        "Один чоловік на місяці сумнівається у власній реальності.",
        "Měsíc (2009)",
        "Astronaut na Měsíci se ocitá v podivné existenci.",
        "https://www.youtube.com/watch?v=SwSlSiJJQXI",
        "Sci‑fi,Drama",
        2,
        "https://www.netflix.com/title/70264888"
    ),
    (
        "Black Swan (2010)",
        "A committed dancer struggles to maintain her sanity after winning the lead role in a production of Swan Lake.",
        "Чёрный лебедь (2010)",
        "Балерина теряет себя, репетируя роль тёмного Лебедя.",
        "Чорний лебідь (2010)",
        "Танець приводить до втрати реальності і себе.",
        "Černý labuť (2010)",
        "Baletka propadá své posedlosti kvůli dokonalosti.",
        "https://www.youtube.com/watch?v=5jaI1XOB-bs",
        "Drama,Thriller",
        2,
        "https://www.netflix.com/title/70258827"
    ),
    (
        "Crouching Tiger, Hidden Dragon (2000)",
        "A warrior reclaims a stolen sword and takes a young nobleman's fate into her hands.",
        "Крадущийся тигр, затаившийся дракон (2000)",
        "Воительница стремится вернуть украденный меч и меняться самой.",
        "Тигр, що ховається, дракон (2000)",
        "Воїнка повертає меч і змінює долю іншого.",
        "Tygr, který neslyší (2000)",
        "Bojovnice se vydává pomstít, střeží osud jiného.",
        "https://www.youtube.com/watch?v=UoV9Tx-5XKA",
        "Action,Fantasy,Drama",
        3,
        "https://www.netflix.com/title/60003998"
    ),
    (
        "The Truman Show (1998)",
        "An insurance salesman discovers his entire life is actually a TV show broadcasted live.",
        "Шоу Трумана (1998)",
        "Мужчина узнаёт, что его жизнь — это телевизионная постановка.",
        "Шоу Трумана (1998)",
        "Чоловік розуміє, що все його життя — шоу для глядачів.",
        "Truman Show (1998)",
        "Po celém světě sledují život toho, kdo to neví.",
        "https://www.youtube.com/watch?v=2SvWeLwfZZY",
        "Drama,Fantasy",
        2,
        "https://www.netflix.com/title/60011620"
    ),
    (
        "The Social Network (2010)",
        "The founding of Facebook leads to lawsuits and clashes over ownership and generosity.",
        "Социальная сеть (2010)",
        "История создания Facebook и конфликтов между основателями.",
        "Соціальна мережа (2010)",
        "Як створення Facebook розділило співзасновників.",
        "Síť (2010)",
        "Zakládání Facebooku a právní bitvy za vlastnictví.",
        "https://www.youtube.com/watch?v=lB95KLmpLR4",
        "Drama,Biography,Detective",
        2,
        "https://www.netflix.com/title/70132603"
    ),
    (
        "Mystic River (2003)",
        "Three men are reunited by a tragedy from their childhood involving the murder of a daughter.",
        "Таинственная река (2003)",
        "Трагедия в детстве возвращает друзей к расследованию.",
        "Таємнича ріка (2003)",
        "Тріо друзів возз'єднується через стару трагедію.",
        "Tajemná řeka (2003)",
        "Přátelé se znovu setkávají kvůli staré záhadě.",
        "https://www.youtube.com/watch?v=HUECWi5pX7o",
        "Crime,Drama,Detective",
        3,
        "https://www.netflix.com/title/60005022"
    ),
    (
        "Nocturnal Animals (2016)",
        "An art gallery owner is haunted by her ex-husband's violent novel.",
        "У ночі тварини (2016)",
        "Женщина оценивает своё прошлое через жесткую историю в книге.",
        "Нічні тварини (2016)",
        "Жінка переживає перевтворення минулого через книгу свого колишнього.",
        "Noční zvířata (2016)",
        "Žena čelí traumatu skrze román bývalého muže.",
        "https://www.youtube.com/watch?v=YmRVbm-u2jU",
        "Drama,Thriller",
        2,
        "https://www.netflix.com/title/70308127"
    ),
    (
        "Inglourious Basterds (2009)",
        "In Nazi‑occupied France, a plan to assassinate Hitler unfolds with various factions participating.",
        "Бесславные ублюдки (2009)",
        "План мести в оккупированной чужой Франции.",
        "Безславні виродки (2009)",
        "Українські солдати діють у тилу ворога з метою вбити Гітлера.",
        "Hanební parchanti (2009)",
        "Partyzáni se snaží zastavit totalitní režim.",
        "https://www.youtube.com/watch?v=KnrRy6kSFF0",
        "Action,War,Drama",
        3,
        "https://www.netflix.com/title/70143836"
    ),
    (
        "Inside Llewyn Davis (2013)",
        "A week in the life of a 1960s folk singer navigating the Greenwich Village music scene.",
        "Внутри Льюина Дэвиса (2013)",
        "Фолк-певец переживает творческий кризис в Нью-Йорке.",
        "Внутрішній Льюїн Девіс (2013)",
        "Музикант шукає свій шлях у музичній сцені Village.",
        "Inside Llewyn Davis (2013)",
        "Folk zpěvák se potácí v osobní a umělecké krizi.",
        "https://www.youtube.com/watch?v=mnG9L0ThKDo",
        "Drama,Musical",
        2,
        "https://www.netflix.com/title/80031629"
    ),
    (
        "The Last Samurai (2003)",
        "An American military advisor embraces the Samurai culture he was hired to destroy.",
        "Последний самурай (2003)",
        "Ветеран войны меняет сторону и находит новую жизнь среди самураев.",
        "Останній самурай (2003)",
        "Американець відкриває культуру самураїв і змінюється.",
        "Poslední samuraj (2003)",
        "Americký voják přechází na stranu samurajů a ищет искупление.",
        "https://www.youtube.com/watch?v=yUjNXjuyYfo",
        "Action,Drama,Adventure",
        3,
        "https://www.netflix.com/title/60018001"
    ),
    (
        "Brooklyn (2015)",
        "An Irish immigrant lands in 1950s Brooklyn, where she falls in love and faces difficult choices.",
        "Бруклин (2015)",
        "Иммигрантка старшего поколения строит новую жизнь в Нью-Йорке.",
        "Бруклін (2015)",
        "Ірландка будує життя в Брукліні та обирає між домом і любовью.",
        "Brooklyn (2015)",
        "Iranka hledá štěstí ve 1950s New Yorku.",
        "https://www.youtube.com/watch?v=H3MPgZEhaho",
        "Drama,Romance",
        2,
        "https://www.netflix.com/title/80024392"
    ),
    (
        
        "Hereditary (2018)",
        "A family begins to unravel dark secrets about their ancestry as unsettling events unfold after a death.",
        "Реинкарнация (2018)",
        "После смерти бабушки жизнь семьи начинает рушиться из-за сверхъестественных событий.",
        "Спадщина (2018)",
        "Смерть бабусі запускає низку моторошних подій у родині.",
        "Dědictví (2018)",
        "Rodina odhaluje temné rodinné tajemství po smrti matriarchy.",
        "https://www.youtube.com/watch?v=4QvetC한다",
        "Horror,Drama",
        2,
        "https://www.netflix.com/title/80223994"
    ),
    (
        "The Prestige (2006)",
        "Two magicians engage in a deadly rivalry to create the ultimate stage illusion.",
        "Престиж (2006)",
        "Два фокусника соревнуются за создание идеального трюка, не думая о последствиях.",
        "Престиж (2006)",
        "Двоє ілюзіоністів змагаються за найкращу сценічну ілюзію.",
        "Dokonalý trik (2006)",
        "Dva kouzelníci soupeří o dokonalý trik za každou cenu.",
        "https://www.youtube.com/watch?v=o4gHCmTQDVI",
        "Thriller,Drama,Detective",
        2,
        "https://www.netflix.com/title/70057382"
    ),
    (
        "Spotlight (2015)",
        "The true story of how the Boston Globe uncovered systemic abuse in the Catholic Church.",
        "В центре внимания (2015)",
        "Журналисты раскрывают масштабный скандал в католической церкви.",
        "У центрі уваги (2015)",
        "Журналісти розкривають системне зло в церкві.",
        "Ve stínu (2015)",
        "Novináři bojují za pravdu proti mocným institucím.",
        "https://www.youtube.com/watch?v=MBsYqlOqe9k",
        "Drama,Detective,Biography",
        2,
        "https://www.netflix.com/title/80014218"
    ),
    (
        "No Country for Old Men (2007)",
        "Violence and mayhem ensue after a hunter stumbles upon drug money in the desert.",
        "Старикам тут не место (2007)",
        "Охотник находит мешок с деньгами — и становится мишенью опасных убийц.",
        "Старим тут не місце (2007)",
        "Мисливець натикається на гроші, але поплатиться за це жизнью.",
        "No Country for Old Men (2007)",
        "Lovci peněz se stávají cílem bezohledných vrahů.",
        "https://www.youtube.com/watch?v=38A__WT3-o0",
        "Crime,Drama,Thriller",
        3,
        "https://www.netflix.com/title/70010831"
    ),
    (
        "District 9 (2009)",
        "Aliens in detention after crash-landing are segregated and exploited until one man is transformed.",
        "Район №9 (2009)",
        "После крушения пришельцы живут в лагере, пока один мужчина не меняется навсегда.",
        "Район №9 (2009)",
        "Після катастрофи прибульці ув’язнені в зони та експлуатуються людиною.",
        "District 9 (2009)",
        "Mimozemšťané jsou vězněni v ghettu – jeden člověk to změní.",
        "https://www.youtube.com/watch?v=FhHRjrUJLdw",
        "Sci‑fi,Action,Drama",
        2,
        "https://www.netflix.com/title/70136117"
    ),
    (
        "The Wolf of Wall Street (2013)",
        "Based on the true story of Jordan Belfort, from his rise to a stockbroker to his fall due to corruption.",
        "Волк с Уолл‑стрит (2013)",
        "История брокера, который достиг богатства, но погряз в мошенничестве.",
        "Вовк з Уолл‑стріт (2013)",
        "Фінансова імперія валиться из-за ненаситної жадоби.",
        "Vlk z Wall Street (2013)",
        "Jordan Belfort dosáhne bohatství, ale vše ztratí kvůli sobectví.",
        "https://www.youtube.com/watch?v=iszwuX1AK6A",
        "Drama,Crime,Comedy",
        3,
        "https://www.netflix.com/title/70251562"
    ),
    (
        "Pan's Labyrinth (2006)",
        "A girl in Francoist Spain escapes reality in a mythical labyrinth.",
        "Лабиринт Фавна (2006)",
        "Девочка открывает мир фантазий, полный чудес и опасностей.",
        "Лабіринт Фавна (2006)",
        "Дівчинка тікає у фантазію, щоб пережити реальність диктатури.",
        "Faunův labyrint (2006)",
        "Dívka poznává tajemný svět za hranicemi reality.",
        "https://www.youtube.com/watch?v=EqYiSlkvRuw",
        "Fantasy,War,Drama",
        2,
        "https://www.netflix.com/title/70054045"
    ),
    (
        "Moonlight (2016)",
        "A young African-American man grapples with his identity as he grows up in a rough Miami neighborhood.",
        "Лунный свет (2016)",
        "История взросления молодого чернокожего мужчины в Маями.",
        "Місячне світло (2016)",
        "Хлопець шукає себе у хаосі неблагополучного середовища.",
        "Moonlight (2016)",
        "Mladík hledá sám sebe ve světě plném výzev.",
        "https://www.youtube.com/watch?v=9NJj12tJzqc",
        "Drama",
        2,
        "https://www.netflix.com/title/80121348"
    ),
    (
        "Her (2013)",
        "A lonely writer develops an unlikely relationship with an operating system designed to meet his every need.",
        "Она (2013)",
        "Мужчина влюбляется в искусственный интеллект.",
        "Вона (2013)",
        "Самотній чоловік знаходить кохання у програмі.",
        "Ona (2013)",
        "Osamělý muž naváže vztah s operačním systémem.",
        "https://www.youtube.com/watch?v=WzV6mXIOVl4",
        "Sci‑fi,Drama,Romance",
        2,
        "https://www.netflix.com/title/70278988"
    ),
    (
        "Zodiac (2007)",
        "Based on true events, detectives and reporters hunt the Zodiac killer in San Francisco.",
        "Зодиак (2007)",
        "Детективы расследуют серию убийств, оставляя письма с намёками.",
        "Зодіак (2007)",
        "Поліцейські шукають серійного вбивцю по загадковим листам.",
        "Zodiak (2007)",
        "Detektivové pátrají po vrahovi, který terorizuje město.",
        "https://www.youtube.com/watch?v=ybMuM92Ne0I",
        "Crime,Detective,Drama",
        3,
        "https://www.netflix.com/title/70266666"
    ),
    (
        "The Princess Bride (1987)",
        "A young man sets out to rescue his true love after she is kidnapped and a kingdom overruns.",
        "Принцесса-невеста (1987)",
        "Юноша отправляется на борьбу со злом, чтобы спасти свою возлюбленную.",
        "Принцеса-наречена (1987)",
        "Юнак стає на боротьбу за кохання і честь.",
        "Princeska Nevesta (1987)",
        "Mladý muž se vydává na dobrodružství za svou láskou.",
        "https://www.youtube.com/watch?v=WNIPqafd4as",
        "Adventure,Fantasy,Romance",
        1,
        "https://www.netflix.com/title/60003819"
    ),
    (
        "Whiplash (2014)",
        "A promising drummer enrolls at a cut‑throat music conservatory under an abusive instructor.",
        "Одержимость (2014)",
        "Барабанщик борется за признание под нажимом жесткого учителя.",
        "Одержимість (2014)",
        "Молодий музикант намагається досягти успіху у важких умовах.",
        "Whiplash (2014)",
        "Talentovaný bubeník bojuje o uznání.",
        "https://www.youtube.com/watch?v=7d_jQycdQGo",
        "Drama,Musical",
        2,
        "https://www.netflix.com/title/70295172"
    ),
    (
        "The Intouchables (2011)",
        "After his paragliding accident leaves him quadriplegic, a wealthy aristocrat hires a young caregiver.",
        "1+1 (2011)",
        "Богатый аристократ нанимает помощника после травмы.",
        "1+1 (2011)",
        "Багатий аристократ наймає помічника після нещасного випадку.",
        "Nedotknutelní (2011)",
        "Bohatý aristokrat najme pečovu po nehodě.",
        "https://www.youtube.com/watch?v=34WIbmXkewU",
        "Comedy,Drama",
        2,
        "https://www.netflix.com/title/70244571"
    ),
    (
        "Ford v Ferrari (2019)",
        "American car designer Carroll Shelby recruits British driver Ken Miles to build a revolutionary race car.",
        "Форд против Феррари (2019)",
        "Автомобильные конструкторы борются за победу в гонке Le Mans.",
        "Ford проти Ferrari (2019)",
        "Інженери створюють гоночный авто, щоб обігнати конкурента.",
        "Ford v Ferrari (2019)",
        "Americký designer a britský jezdec spojí síly pro závod.",
        "https://www.youtube.com/watch?v=zyY5s_LU8xw",
        "Biography,Drama,Sports",
        2,
        "https://www.netflix.com/title/80200926"
    ),
    (
        "Finding Nemo (2003)",
        "After his son is captured in the Great Barrier Reef and taken to Sydney, a timid clownfish sets out on a journey to bring him home.",
        "В поисках Немо (2003)",
        "Отец-попугай отправляется навстречу океанским приключениям.",
        "У пошуках Немо (2003)",
        "Тато-риба вирушає у подорож океаном, щоб знайти сина.",
        "Hledá se Nemo (2003)",
        "Otec ryba pluje oceánem, aby našel svého syna.",
        "https://www.youtube.com/watch?v=wZdpNglLbt8",
        "Cartoon,Family",
        1,
        "https://www.netflix.com/title/60024977"
    ),
    (
        "The Hurt Locker (2008)",
        "During the Iraq War, a bomb squad team deals with the psychological costs of combat.",
        "Повелитель бури (2008)",
        "Сапёры в Ираке сталкиваются с опасностью и внутренними демонами.",
        "Повелитель бурі (2008)",
        "Сапери переживають війну не тільки физически, а й душевно.",
        "Smrt v nedohlednu (2008)",
        "Pyrotechnická jednotka bojuje s tlakem války.",
        "https://www.youtube.com/watch?v=2GxO2uL4YAMI",
        "War,Drama",
        2,
        "https://www.netflix.com/title/70038083"
    ),
    (
        "Cinderella Man (2005)",
        "The true story of James Braddock, a washed-up boxer who returns to the ring to become a symbol of hope.",
        "Человек, который изменил всё (2005)",
        "Боксер восстанавливает карьеру и становится героем Великой депрессии.",
        "Чоловік, який змінив усе (2005)",
        "Боксер повертається в ринг і стає символом надії.",
        "Cinderella Man (2005)",
        "Ráže Braddock se vrátí do ringu jako symbol naděje.",
        "https://www.youtube.com/watch?v=-SPQdLoAttw",
        "Drama,Biography,Sports",
        2,
        "https://www.netflix.com/title/60004824"
    ),
        (
        "Amélie (2001)",
        "Amélie decides to change the lives of those around her for the better, while grappling with her own isolation.",
        "Амели (2001)",
        "Амели решает позитивно повлиять на жизни окружающих, несмотря на собственную замкнутость.",
        "Амелі (2001)",
        "Амелі вирішує покращити життя інших, але бореться з власною самотністю.",
        "Amélie (2001)",
        "Amélie se rozhodne zlepšit životy lidí kolem sebe, i když sama cítí izolaci.",
        "https://www.youtube.com/watch?v=HUECWi5pX7o",
        "Comedy,Romance,Drama",
        2,
        "https://www.netflix.com/title/60000483"
    ),
    (
        "The Green Mile (1999)",
        "A death row correction officer discovers a gentle giant with miraculous powers that challenge his beliefs.",
        "Зеленая миля (1999)",
        "Сотрудник тюрьмы смерти обнаруживает необычного заключённого с чудодейственными способностями.",
        "Зелена миля (1999)",
        "Тюремний охоронець відкриває дивовижного ув'язненого з надприродними даром.",
        "Zelená míle (1999)",
        "Dozorčí smrti objeví nevšedního vězně s tajemnými schopnostmi.",
        "https://www.youtube.com/watch?v=Ki4haFrqSrw",
        "Drama,Crime,Fantasy",
        3,
        "https://www.netflix.com/title/60011252"
    ),
    (
        "Blade Runner 2049 (2017)",
        "A young blade runner's discovery of a long-buried secret leads him to track down former blade runner Rick Deckard.",
        "Бегущий по лезвию 2049 (2017)",
        "Офицер обнаруживает давно скрытую тайну и ищет бывшего Бегущего по лезвию.",
        "Той, що біжить по лезу 2049 (2017)",
        "Офіцер Blade Runner розслідує давню таємницю і шукає Ріка Декарда.",
        "Blade Runner 2049 (2017)",
        "Mladý Blade Runner objeví dávné tajemství a pátrá po Ricku Deckardovi.",
        "https://www.youtube.com/watch?v=gCcx85zbxz4",
        "Sci‑fi,Drama,Detective",
        3,
        "https://www.netflix.com/title/80188583"
    ),
    (
        "Gone Girl (2014)",
        "With his wife's disappearance having become the focus of an intense media circus, a man sees the spotlight turned on him.",
        "Исчезнувшая (2014)",
        "Жена исчезает, и внимание СМИ падает на её мужа.",
        "Зникла (2014)",
        "Дружина зникає, і весь світ дивиться на її чоловіка.",
        "Zmizelá (2014)",
        "Manželka zmizí a mediální pozornost se obrací na jejího muže.",
        "https://www.youtube.com/watch?v=Ym3LB0lOJ0o",
        "Thriller,Crime,Drama",
        2,
        "https://www.netflix.com/title/70301870"
    ),
    (
        "Life Is Beautiful (1997)",
        "When an open‑hearted Jewish waiter and his son become victims of the Holocaust, he uses humor to protect his son.",
        "Жизнь прекрасна (1997)",
        "Еврейский отец использует юмор, чтобы оградить сына от ужасов концлагеря.",
        "Життя прекрасне (1997)",
        "Батько захищає сина гумором у нацистському таборі.",
        "Život je krásný (1997)",
        "Židovský otec chrání syna humorem během holocaustu.",
        "https://www.youtube.com/watch?v=pAYEQP8gx3w",
        "Comedy,Drama,Historical",
        3,
        "https://www.netflix.com/title/60005031"
    ),
    (
        "The Hunt (2012)",
        "A man becomes the target of mass paranoia when a little girl’s accusation tears his world apart.",
        "Охота (2012)",
        "Мужчину обвиняют в позорном преступлении, и его жизнь рушится.",
        "Полювання (2012)",
        "Чоловіка оголошують винним, і його життя руйнується через фальшиві звинувачення.",
        "Hon (2012)",
        "Muž je neoprávněně obviněn a stává se terčem společenské nenávisti.",
        "https://www.youtube.com/watch?v=2YlR0fE0X0Y",
        "Drama,Crime",
        2,
        "https://www.netflix.com/title/70294815"
    ),
    (
        "The Martian (2015)",
        "An astronaut becomes stranded on Mars after his team assumes him dead, and must find a way to signal to Earth that he is alive.",
        "Марсианин (2015)",
        "Астронавт остаётся на Марсе и борется за выживание.",
        "Марсіянин (2015)",
        "Астронавт залишається на Марсі і шукає спосіб зв’язатися із Землею.",
        "Marťan (2015)",
        "Astronaut zůstane na Marsu a snaží se kontaktovat Zemi.",
        "https://www.youtube.com/watch?v=ej3ioOneTy8",
        "Sci‑fi,Adventure,Drama",
        2,
        "https://www.netflix.com/title/80133331"
    ),
    (
        "Children of Heaven (1997)",
        "A brother and sister pair scheme to keep one pair of shoes between them after one is lost.",
        "Дети небес (1997)",
        "Брат и сестра делят одну пару туфель после того, как одна теряется.",
        "Діти небес (1997)",
        "Брат і сестра мають одну пару взуття після загубленої.",
        "Děti nebe (1997)",
        "Sourozenci sdílí jednu botu poté, co se ztratí.",
        "https://www.youtube.com/watch?v=ua7K9tvOElc",
        "Family,Drama",
        1,
        "https://www.netflix.com/title/60033811"
    ),
    (
        "Dead Poets Society (1989)",
        "English teacher John Keating inspires his students through poetry to seize the day.",
        "Общество мёртвых поэтов (1989)",
        "Учитель вдохновляет учеников жить насыщенно и смело.",
        "Товариство мертвих поетів (1989)",
        "Учитель надихає студентів, щоб жити повно та відважно.",
        "Společnost mrtvých básníků (1989)",
        "Učitel inspiruje studenty skrze poezii k tomu, aby žili naplno.",
        "https://www.youtube.com/watch?v=wrKi4EZ1mgA",
        "Drama,Family",
        2,
        "https://www.netflix.com/title/60000463"
    ),
    (
        "The Shawshank Redemption (1994)",
        "Imprisoned banker Andy Dufresne builds friendship and hope while enduring decades of prison life.",
        "Побег из Шоушенка (1994)",
        "Бухгалтер Энди Дюфрейн, обвинённый в смерти жены, находит семью в заключенных.",
        "Втеча з Шоушенка (1994)",
        "Банкір Андрі живе надією й дружбою у стінах в’язниці.",
        "Vykoupení z věznice Shawshank (1994)",
        "Bankéř Andy nachází přátele a naději ve vězení.",
        "https://www.youtube.com/watch?v=6hB3S9bIaco",
        "Drama,Crime",
        3,
        "https://www.netflix.com/title/70005379"
    ),
    (
        "Rocky (1976)",
        "A small-time boxer gets a chance to fight the heavyweight champion and strives for dignity.",
        "Рокки (1976)",
        "Боксер-любитель получает шанс всей жизни — бой с чемпионом.",
        "Рокі (1976)",
        "Бідний боксер отримує шанс змагатися з чемпіоном.",
        "Rocky (1976)",
        "Pouliční boxer dostane šanci bojovat o titul.",
        "https://www.youtube.com/watch?v=7RYpJAUMo2M",
        "Drama,Sports",
        2,
        "https://www.netflix.com/title/60027979"
    ),
    (
        "Memories of Murder (2003)",
        "Korean detectives struggle to solve the country's first serial murders in the 1980s.",
        "Воспоминания об убийстве (2003)",
        "Корейские детективы пытаются поймать серийного убийцу в сельской провинции.",
        "Спогади про вбивство (2003)",
        "Корейські детективи розслідують перші випадкові самогубства серійного вбивці.",
        "Vzpomínky na vraždu (2003)",
        "Korejští detektivové se snaží dopadnout sériového vraha.",
        "https://www.youtube.com/watch?v=DhRKpb0e-k0",
        "Crime,Detective,Drama",
        3,
        "https://www.netflix.com/title/70088455"
    ),
    (
        "Gran Torino (2008)",
        "A disgruntled war veteran faces his prejudices when tasked to help a young neighbor boy.",
        "Гран Торино (2008)",
        "Старик-ветеран войны становится наставником соседского мальчика и меняется.",
        "Гран Торіно (2008)",
        "Ветеран війни змінюється, коли допомагає сусідському хлопчику.",
        "Gran Torino (2008)",
        "Veterán se promění, když pomáhá sousedovu chlapci.",
        "https://www.youtube.com/watch?v=RMhbr2XQblk",
        "Drama,Crime",
        2,
        "https://www.netflix.com/title/60012077"
    ),
    (
        "Eternal Sunshine of the Spotless Mind (2004)",
        "A couple undergoes a procedure to erase memories of each other after a painful breakup.",
        "Вечное сияние чистого разума (2004)",
        "Пара решает стереть друг друга из памяти после болезненного расставания.",
        "Вічне сяйво чистого розуму (2004)",
        "Пара проходить процедуру стирання спогадів після розставання.",
        "Věčné slunce neposkvrněné mysli (2004)",
        "Pár podstupuje proceduru vymazání vzpomínek po rozchodu.",
        "https://www.youtube.com/watch?v=0zFywiAhvpf",
        "Drama,Romance,Sci‑fi",
        2,
        "https://www.netflix.com/title/70141913"
    ),
    (
        "Mad Max: Fury Road (2015)",
        "In a post-apocalyptic wasteland, Max teams up with Furiosa to escape from a tyrant ruling the land.",
        "Безумный Макс: Дорога ярости (2015)",
        "Макс помогает Фуриозе сбежать от тирана в постапокалиптическом мире.",
        "Божевільний Макс: Дорога люті (2015)",
        "Макс разом із Фуріозою рятуються від диктатора у пустошах.",
        "Šílený Max: Zběsilá cesta (2015)",
        "Max se spojí s Furiosou, aby unikli tyranskému vládci v postapokalyptické pustině.",
        "https://www.youtube.com/watch?v=hEJnMQG9ev8",
        "Action,Adventure,Drama",
        2,
        "https://www.netflix.com/title/80057159"
    ),
    (
        "Spotlight (2015)",
        "The true story of how the Boston Globe uncovered systemic child abuse by Catholic priests.",
        "В центре внимания (2015)",
        "Репортеры Boston Globe раскрывают систематическое насилие священников.",
        "У центрі уваги (2015)",
        "Журналісти розслідують масштабне зловживання у католицькій церкві.",
        "Ve stínu (2015)",
        "Novináři odhalují systémové zneužívání ze strany katolických duchovních.",
        "https://www.youtube.com/watch?v/MBsYqlOqe9k",
        "Drama,Detective,Biography",
        2,
        "https://www.netflix.com/title/80014218"
    ),
    (
        "Zootopia (2016)",
        "In a city of anthropomorphic animals, a rookie bunny cop and a cynical con artist fox uncover a conspiracy.",
        "Зверополис (2016)",
        "Кролик-полицейский и лис-мошенник распутывают заговор в антропоморфном городе.",
        "Зоополіс (2016)",
        "Кролик у поліції та хитра лисиця розкривають змову у світі тварин.",
        "Zootropolis (2016)",
        "Město zvířat; začínající policejní zajíček a liška podvodnice odhalují spiknutí.",
        "https://www.youtube.com/watch?v=jWM0ct-OLsM",
        "Cartoon,Comedy,Family",
        2,
        "https://www.netflix.com/title/80033785"
    ),
    (
        "Slumdog Millionaire (2008)",
        "A Mumbai teen reflects on his life after being accused of cheating on the Indian version of 'Who Wants to Be a Millionaire?'.",
        "Миллионер из трущоб (2008)",
        "Подозреваемый в мошенничестве подросток рассказывает свою жизненную историю.",
        "Мільйонер із нетрів (2008)",
        "Підліток з нетрів Мумбаї розкриває своє життя після обвинувачення.",
        "Slumdog Millionaire (2008)",
        "Teenager z bombajské čtvrti odhaluje životní příběh poté, co je obviněn z podvodu.",
        "https://www.youtube.com/watch?v=AIzbwV7on6Q",
        "Drama,Romance",
        2,
        "https://www.netflix.com/title/70058583"
    ),
    (
        "Get Out (2017)",
        "A young African-American visits his white girlfriend's family and uncovers disturbing secrets.",
        "Прочь (2017)",
        "Афроамериканец приезжает к семье подруги и сталкивается с ужасами.",
        "Геть (2017)",
        "Молодий чоловік відвідує родину дівчини і стикається з жахливими таємницями.",
        "Uteč (2017)",
        "Mladý Afro‑Američan navštíví rodiče přítelkyně a objeví děsivé tajemství.",
        "https://www.youtube.com/watch?v=DzfpyUB60YY",
        "Thriller,Horror",
        2,
        "https://www.netflix.com/title/80108975"
    ),
    (
        "Logan (2017)",
        "In a bleak future, an aged Wolverine cares for an ailing Professor X and protects a mutant child.",
        "Логан (2017)",
        "Пожилой Росомаха заботится о профессоре Икс и защищает мутанта-девочку.",
        "Логан (2017)",
        "Постарілий Росомаха опікується професором Ікс та захищає дитину із здібностями.",
        "Logan (2017)",
        "Stárnoucí Wolverine chrání nemocného profesora X a mutanta-dívku v pochmurné budoucnosti.",
        "https://www.youtube.com/watch?v=Div0iP65aZo",
        "Action,Drama",
        2,
        "https://www.netflix.com/title/80185212"
    ),
    (
        "City of God (2002)",
        "Two boys growing up in a violent neighborhood of Rio de Janeiro take different paths – one becomes a photographer, the other a gangster.",
        "Город Бога (2002)",
        "Мальчики растут в трущобах Рио и выбирают разные пути в жизни.",
        "Місто Бога (2002)",
        "Хлопці з фавел вибирають між фотографией та преступлением.",
        "Město Boží (2002)",
        "Dva kluci z chudinské čtvrti Rio de Janeiro jdou rozdílnými cestami – jeden je fotograf, druhý gangster.",
        "https://www.youtube.com/watch?v=9Auq9mYxFEE",
        "Crime,Drama",
        3,
        "https://www.netflix.com/title/70044940"
    ),
    (
        "Pan's Labyrinth (2006)",
        "A young girl in Francoist Spain meets a mythical faun who leads her into a magical but dangerous world.",
        "Лабиринт Фавна (2006)",
        "Девочка открывает магический мир, полный чудес и опасностей.",
        "Лабіринт Фавна (2006)",
        "Дівчинка потрапляє до магії у темному світі диктатури.",
        "Faunův labyrint (2006)",
        "Dívka vstupuje do kouzelného a nebezpečného světa za Frankova režimu.",
        "https://www.youtube.com/watch?v=EqYiSlkvRuw",
        "Fantasy,Historical,Drama",
        2,
        "https://www.netflix.com/title/70054045"
    ),
    (
        "Django Unchained (2012)",
        "With the help of a German bounty hunter, a freed slave sets out to rescue his wife from a brutal plantation owner.",
        "Джанго освобождённый (2012)",
        "Освобождённый раб становится охотником за головами, чтобы спасти жену.",
        "Джанґо звільнений (2012)",
        "Колишній раб об’єднується з мисливцем за головами заради порятунку дружини.",
        "Django Unchained (2012)",
        "Osvobozený otrok se spojí s lovcem odměn, aby zachránil ženu.",
        "https://www.youtube.com/watch?v=eUdM9vrCbow",
        "Western,Drama,Crime",
        3,
        "https://www.netflix.com/title/80017473"
    ),
    (
        "Up (2009)",
        "An elderly widower ties thousands of balloons to his house and flies to South America to fulfill a promise to his late wife.",
        "Вверх (2009)",
        "Пожилой вдовец улетает в Южную Америку на доме с воздушными шарами.",
        "Вгору (2009)",
        "Пенсіонер відлітає у Південну Америку на будинку з повітряними кулями.",
        "Vzhůru dolů (2009)",
        "Starý vdovec létá do Jižní Ameriky přivázaný k tisícům balónků.",
        "https://www.youtube.com/watch?v=pkqzFUhGPJg",
        "Cartoon,Family,Adventure",
        2,
        "https://www.netflix.com/title/70153404"
    ),
    (
        "The Prestige (2006)",
        "Two magicians engage in a deadly rivalry to create the ultimate stage illusion.",
        "Престиж (2006)",
        "Два фокусника соревнуются в создании идеального трюка, не жалея жертв.",
        "Престиж (2006)",
        "Двоє фокусників змагаються за найкращий ілюзіонний трюк.",
        "Dokonalý trik (2006)",
        "Dva kouzelníci soupeří o největší scénickou iluzi.",
        "https://www.youtube.com/watch?v=o4gHCmTQDVI",
        "Thriller,Drama,Mystery",
        2,
        "https://www.netflix.com/title/70057382"
    ),
    (
        "Life of Pi (2012)",
        "After a shipwreck, a young man survives on a lifeboat with a Bengal tiger in the Pacific.",
        "Жизнь Пи (2012)",
        "Выживший после крушения молодой человек путешествует с тигром на лодке.",
        "Життя Пі (2012)",
        "Після аварії човна хлопець виживає разом із тигром у океані.",
        "Pí a jeho život (2012)",
        "Mladík přežije námořní tragédii na záchranném člunu s tygrem.",
        "https://www.youtube.com/watch?v=jY9h38lX3tY",
        "Adventure,Drama",
        3,
        "https://www.netflix.com/title/70283253"
    ),
    (
        "Shaolin Soccer (2001)",
        "A former Shaolin monk reunites his brothers to form a soccer team that applies martial arts skills.",
        "Шаолиньский футбол (2001)",
        "Монах организует футбольную команду с боевыми приёмами.",
        "Шаоліньський футбол (2001)",
        "Колишній монах збирає команду футболістів з бойовими приёмами.",
        "Shaolin fotbal (2001)",
        "Bývalý mnich založí fotbalový tým bojující kung‑fu technikou.",
        "https://www.youtube.com/watch?v=7sxVYHRt5xY",
        "Comedy,Action,Fantasy",
        1,
        "https://www.netflix.com/title/80152000"
    ),
    (
        "Brokeback Mountain (2005)",
        "The forbidden affair between two cowboys in the American West challenges societal norms and spans decades.",
        "Горбатая гора (2005)",
        "Запретная любовь ковбоев на фоне сурового Запада.",
        "Горбатая гора (2005)",
        "Заборонене кохання двох ковбоїв на Дикому Заході.",
        "Zapadní spáč (2005)",
        "Zakázaný vztah dvou kovbojů v Americkém Západě.",
        "https://www.youtube.com/watch?v=nn_7qYgS3KU",
        "Drama,Romance",
        2,
        "https://www.netflix.com/title/60002427"
    ),
    (
        "Hidden Figures (2016)",
        "The untold story of African-American women mathematicians who served at NASA during the Space Race.",
        "Скрытые фигуры (2016)",
        "Чернокожие женщины-математики работали на NASA и изменили ход истории.",
        "Сховані фігури (2016)",
        "Жінки‑математики працювали в NASA під час космічної гонки.",
        "Skryté figury (2016)",
        "Neznámý příběh černošských matematiček v NASA.",
        "https://www.youtube.com/watch?v=5wfrDhgUMGI",
        "Biography,History,Drama",
        2,
        "https://www.netflix.com/title/80117400"
    ),
    (
        "Pan's Labyrinth (2006)",
        "In the Falangist Spain of 1944, the bookish young stepdaughter of a sadistic army officer escapes into an eerie but captivating fantasy world.",
        "Лабиринт Фавна (2006)",
        "Молодая девочка попадает в волшебный и опасный мир фантазий в Испании времён Франко.",
        "Лабіринт Фавна (2006)",
        "Молода дівчинка тікає від реальності у світ фантазій.",
        "Faunův labyrint (2006)",
        "Dívka vstupuje do kouzelného světa během španělského fašismu.",
        "https://www.youtube.com/watch?v=EqYiSlkvRuw",
        "Fantasy,War,Drama",
        2,
        "https://www.netflix.com/title/70054045"
    )
,
    (
        "Inside Out (2015)",
        "After young Riley is uprooted from her Midwest life, her emotions conflict on how best to navigate a new city and home.",
        "Головоломка (2015)",
        "После переезда в Сан-Франциско эмоции маленькой Райли пытаются помочь ей справиться с переменами.",
        "Думками навиворіт (2015)",
        "Емоції Райлі намагаються допомогти їй адаптуватися до нового життя в Сан-Франциско.",
        "V hlavě (2015)",
        "Emoce mladé Riley se snaží najít rovnováhu po stěhování do nového města.",
        "https://www.youtube.com/watch?v=seMwpP0yeu4",
        "Cartoon,Family",
        1,
        "https://www.netflix.com/title/80057171"
    ),
    (
        "Gladiator (2000)",
        "A former Roman General sets out to exact vengeance against the corrupt emperor who murdered his family.",
        "Гладиатор (2000)",
        "Бывший генерал Рима мстит за смерть своей семьи и восстаёт против императора.",
        "Гладіатор (2000)",
        "Колишній генерал Риму мстить за свою сім’ю, борючись проти тирана.",
        "Gladiátor (2000)",
        "Bývalý generál se chce pomstít císaři, který zabil jeho rodinu.",
        "https://www.youtube.com/watch?v=owK1qxDselE",
        "Action,Historical,Drama",
        3,
        "https://www.netflix.com/title/60000929"
    ),
    (
        "A Quiet Place (2018)",
        "In a post-apocalyptic world, a family must live in silence while hiding from monsters with ultra-sensitive hearing.",
        "Тихое место (2018)",
        "Семья должна жить в полной тишине, чтобы выжить в мире, наполненном монстрами.",
        "Тихе місце (2018)",
        "Родина має мовчати, щоб вижити серед монстрів, які реагують на звук.",
        "Tiché místo (2018)",
        "Rodina žije v tichu, aby přežila před tvory, kteří loví podle zvuku.",
        "https://www.youtube.com/watch?v=WR7cc5t7tv8",
        "Horror,Thriller",
        2,
        "https://www.netflix.com/title/81021369"
    ),
    (
        "Billy Elliot (2000)",
        "A young boy discovers a passion for ballet in a working-class town and struggles against societal norms.",
        "Билли Эллиот (2000)",
        "Мальчик из шахтёрского города мечтает стать балетным танцором, несмотря на сопротивление окружающих.",
        "Біллі Елліот (2000)",
        "Хлопчик мріє танцювати балет, попри очікування сім’ї та суспільства.",
        "Billy Elliot (2000)",
        "Chlapec sní o baletu navzdory těžké realitě hornického města.",
        "https://www.youtube.com/watch?v=anV8Rfd1QXg",
        "Melodrama,Sports",
        2,
        "https://www.netflix.com/title/60000958"
    ),
    (
        "The Social Dilemma (2020)",
        "Tech experts sound the alarm on the dangerous human impact of social networking.",
        "Социальная дилемма (2020)",
        "Эксперты в области технологий рассказывают о вреде соцсетей для общества.",
        "Соціальна дилема (2020)",
        "Фахівці пояснюють, як соцмережі впливають на психіку та суспільство.",
        "Sociální dilema (2020)",
        "Odborníci varují před nebezpečím sociálních sítí.",
        "https://www.youtube.com/watch?v=uaaC57tcci0",
        "Documentary",
        1,
        "https://www.netflix.com/title/81254224"
    ),
    (
        "Saving Private Ryan (1998)",
        "Following the Normandy Landings, a group of U.S. soldiers go behind enemy lines to retrieve a paratrooper.",
        "Спасти рядового Райана (1998)",
        "Отряд отправляется в тыл врага, чтобы вернуть домой единственного выжившего брата.",
        "Врятувати рядового Раяна (1998)",
        "Загін шукає солдата, якого потрібно повернути додому після загибелі його братів.",
        "Zachraňte vojína Ryana (1998)",
        "Jednotka se vydává za nepřátelskou linii zachránit vojáka Ryana.",
        "https://www.youtube.com/watch?v=vwAxi4A3Qx0",
        "Military,Drama",
        3,
        "https://www.netflix.com/title/118153"
    ),
    (
        "Whiplash (2014)",
        "A promising drummer enrolls at a cut-throat music conservatory where his dreams are mentored by an abusive instructor.",
        "Одержимость (2014)",
        "Молодой барабанщик борется за успех в элитной музыкальной школе под давлением жестокого наставника.",
        "Одержимість (2014)",
        "Барабанщик змагається за визнання, навчаючись у суворого вчителя.",
        "Whiplash (2014)",
        "Talentovaný bubeník čelí tvrdé výuce v prestižní hudební škole.",
        "https://www.youtube.com/watch?v=7d_jQycdQGo",
        "Drama,Musical",
        2,
        "https://www.netflix.com/title/70295172"
    ),
    (
        "Rango (2011)",
        "A pet chameleon accidentally ends up in a town in the Wild West and becomes its unlikely hero.",
        "Ранго (2011)",
        "Хамелеон случайно становится шерифом в городе на Диком Западе.",
        "Ранго (2011)",
        "Хамелеон стає шерифом на Дикому Заході.",
        "Rango (2011)",
        "Chameleon se stane nečekaným hrdinou městečka na Divokém západě.",
        "https://www.youtube.com/watch?v=k-OOfW6wWyQ",
        "Western,Cartoon,Comedy",
        1,
        "https://www.netflix.com/title/70139489"
    ),
    (
        "Moneyball (2011)",
        "Oakland A's general manager Billy Beane uses data analysis to assemble a competitive baseball team.",
        "Человек, который изменил всё (2011)",
        "Менеджер команды использует статистику, чтобы создать сильную команду с минимальным бюджетом.",
        "Людина, яка змінила все (2011)",
        "Біллі Бін змінює правила гри в бейсболі завдяки аналітиці.",
        "Moneyball (2011)",
        "Manažer baseballového týmu používá statistiku pro vytvoření vítězného týmu.",
        "https://www.youtube.com/watch?v=-4QPVo0UIzc",
        "Biography,Sports,Drama",
        2,
        "https://www.netflix.com/title/70177057"
    ),
    (
        "The Conjuring (2013)",
        "Paranormal investigators help a family terrorized by a dark presence in their farmhouse.",
        "Заклятие (2013)",
        "Семья сталкивается со злом, и им помогают известные охотники за привидениями.",
        "Закляття (2013)",
        "Родина зазнає жахів у своєму будинку, а допомогти можуть лише фахівці з паранормального.",
        "V zajetí démonů (2013)",
        "Rodině pomáhají lovci duchů čelit zlu v jejich domě.",
        "https://www.youtube.com/watch?v=k10ETZ41q5o",
        "Horror,Thriller",
        2,
        "https://www.netflix.com/title/70251894"
    ),
    (
        "The Shawshank Redemption (1994)",
        "Imprisoned in the 1940s for the double murder of his wife and her lover, upstanding banker Andy Dufresne begins a new life at the Shawshank prison, where he puts his accounting skills to work for an amoral warden. During his long stretch in prison, Dufresne comes to be admired by the other inmates -- including an older prisoner named Red -- for his integrity and unquenchable sense of hope.",  #2 (EN description)
        "Побег из Шоушенка (1994)",
        "Бухгалтер Энди Дюфрейн обвинён в убийстве собственной жены и её любовника. Оказавшись в тюрьме под названием Шоушенк, он сталкивается с жестокостью и беззаконием, царящими по обе стороны решётки. Каждый, кто попадает в эти стены, становится их рабом до конца жизни. Но Энди, обладающий живым умом и доброй душой, находит подход как к заключённым, так и к охранникам, добиваясь их особого к себе расположения.",  #4 (RU description)
        "Втеча з Шоушенка (1994)",
        "Енді Дюфрейна, віцепрезидента солідного банку, засуджують до двох довічних ув’язнень за обвинуваченням у вбивстві дружини та її коханця. Він відбуває ув’язнення в тюрмі Шоушенка, де проходить усі кола пекла, проявляючи незвичайну мужність, завзятість і холоднокровність.",
        "Vykoupení z věznice Shawshank (1994)",
        "Andy Dufresne přichází do vězení v Shawshanku jako nový vězeň podezřelý z vraždy. Spřátelí se s doživotně odsouzeným Redem a společně se snaží přežít v nelidském prostředí vězeňského systému. Odmítají upadnout do rezignace a dodávají naději sobě i spoluvězňům.",
        "https://youtu.be/PLl99DlL6b4?si=AHoBK5lkZZYRjHIY",
        "Drama,Crime",
        2,
        "https://www.netflix.com/cz-en/title/70005379"
    ),
    (
        "The Godfather (1972)",
        "The aging patriarch of an organized crime dynasty transfers control of his clandestine empire to his reluctant son.",
        "Крёстный отец (1972)",
        "Молодой Майкл Корлеоне не хочет иметь ничего общего с криминальным бизнесом его отца. Но обстоятельства вынуждают его встать во главе мафии и взять на себя управление делами семьи.",
        "Хрещений батько (1972)",
        "Старий дон мафіозної родини передає керівництво своєму сину, який спочатку не хоче мати нічого спільного зі злочинним світом.",
        "Kmotr (1972)",
        "Stárnoucí kmotr mafiánské rodiny předává vedení neochotnému synovi.",
        "https://www.youtube.com/watch?v=sY1S34973zA",
        "Drama,Crime",
        3,
        "https://www.netflix.com/title/60011152"
    ),
    (
        "The Dark Knight (2008)",
        "When the menace known as the Joker wreaks havoc, Batman must accept one of the greatest psychological and physical tests of his ability to fight injustice.",
        "Тёмный рыцарь (2008)",
        "Бэтмен сталкивается с Джокером — преступным гением, сеющим хаос в Готэме. Он должен преодолеть свои внутренние конфликты, чтобы спасти город.",
        "Темний лицар (2008)",
        "Бетмен протистоїть Джокеру, який несе хаос у Готем. Герой має зробити складний моральний вибір.",
        "Temný rytíř (2008)",
        "Batman čelí chaosu, který přináší Joker, a musí ochránit město před zlem.",
        "https://www.youtube.com/watch?v=EXeTwQWrcwY",
        "Action,Crime,Drama",
        2,
        "https://www.netflix.com/title/70079583"
    ),
    (
        "Pulp Fiction (1994)",
        "The lives of two mob hitmen, a boxer, a gangster's wife, and a pair of diner bandits intertwine in four tales of violence and redemption.",
        "Криминальное чтиво (1994)",
        "Истории гангстеров, боксёров, бандитов и случайных встреч переплетаются в одном из самых культовых фильмов 90-х.",
        "Кримінальне чтиво (1994)",
        "Історії гангстерів, боксерів, злодіїв і неочікуваних зустрічей переплітаються в одному фільмі.",
        "Pulp Fiction: Historky z podsvětí (1994)",
        "Příběhy zabijáků, boxera a dalších postav se prolínají v kultovním filmu 90. let.",
        "https://www.youtube.com/watch?v=s7EdQ4FqbhY",
        "Crime,Drama",
        3,
        "https://www.netflix.com/title/880640"
    ),
    (
        "Inception (2010)",
        "A thief who steals corporate secrets through dream-sharing technology is given a task to plant an idea into a CEO's mind.",
        "Начало (2010)",
        "Профессиональный вор внедряется в сны других людей, чтобы украсть или вложить идеи в их подсознание.",
        "Початок (2010)",
        "Злодій проникає в сни інших людей, щоб вкрасти або нав’язати ідеї.",
        "Počátek (2010)",
        "Zloděj vstupuje do snů ostatních lidí a manipuluje jejich myslí.",
        "https://www.youtube.com/watch?v=YoHD9XEInc0",
        "Sci-fi,Action",
        2,
        "https://www.netflix.com/title/70131314"
    ),
    (
        "Forrest Gump (1994)",
        "The presidencies of Kennedy and Johnson, Vietnam, and Watergate unfold through the perspective of an Alabama man with a low IQ.",
        "Форрест Гамп (1994)",
        "Форрест — добродушный человек с низким IQ, но с добрым сердцем. Его жизнь — череда случайных, но удивительных событий.",
        "Форрест Гамп (1994)",
        "Форрест — щирий і наївний чоловік, який переживає історичні події США.",
        "Forrest Gump (1994)",
        "Forrest je prostý muž, který se nevědomky stává součástí velkých dějin.",
        "https://www.youtube.com/watch?v=bLvqoHBptjg",
        "Drama,Romance",
        2,
        "https://www.netflix.com/title/60000724"
    ),
    (
        "The Matrix (1999)",
        "A computer hacker learns about the true nature of reality and his role in the war against its controllers.",
        "Матрица (1999)",
        "Хакер Нео узнаёт, что его мир — иллюзия, созданная машинами, чтобы подчинить человечество.",
        "Матриця (1999)",
        "Хакер відкриває, що світ — симуляція, створена машинами.",
        "Matrix (1999)",
        "Hacker odhalí, že svět kolem něj je jen iluze řízená stroji.",
        "https://www.youtube.com/watch?v=vKQi3bBA1y8",
        "Action,Sci-fi",
        2,
        "https://www.netflix.com/title/20557937"
    ),
    (
        "Schindler's List (1993)",
        "In German-occupied Poland, Oskar Schindler becomes concerned for his Jewish workforce after witnessing their persecution.",
        "Список Шиндлера (1993)",
        "Оскар Шиндлер спасает более тысячи евреев во время Холокоста, используя свою фабрику как убежище.",
        "Список Шиндлера (1993)",
        "Оскар Шиндлер рятує євреїв, приховуючи їх на своїй фабриці.",
        "Schindlerův seznam (1993)",
        "Německý podnikatel Schindler chrání židovské pracovníky během holokaustu.",
        "https://www.youtube.com/watch?v=gG22XNhtnoY",
        "Drama,History,War",
        3,
        "https://www.netflix.com/title/60036359"
    ),
    (
        "Fight Club (1999)",
        "An insomniac office worker and a soap maker form an underground fight club that evolves into something much more.",
        "Бойцовский клуб (1999)",
        "Устав от рутины, офисный работник создаёт подпольный бойцовский клуб с харизматичным Тайлером Дёрденом.",
        "Бійцівський клуб (1999)",
        "Офісний працівник створює бійцівський клуб, щоб знайти сенс життя.",
        "Klub rváčů (1999)",
        "Zaměstnanec firmy zakládá bojový klub, aby se zbavil frustrace.",
        "https://www.youtube.com/watch?v=SUXWAEX2jlg",
        "Drama",
        2,
        "https://www.netflix.com/title/26004747"
    ),
    (
        "Interstellar (2014)",
        "A team of explorers travel through a wormhole in space in an attempt to ensure humanity's survival.",
        "Интерстеллар (2014)",
        "Группа учёных отправляется в космос через червоточину в поисках нового дома для человечества.",
        "Інтерстеллар (2014)",
        "Команда вчених летить крізь червоточину, щоб знайти нову планету.",
        "Interstellar (2014)",
        "Tým vědců cestuje červí dírou, aby zachránil lidstvo.",
        "https://www.youtube.com/watch?v=zSWdZVtXT7E",
        "Sci-fi,Adventure,Drama",
        3,
        "https://www.netflix.com/title/70305903"
    )
]

# Вставка данных
cursor.executemany("""
INSERT INTO movies (
    title_en,
    description_en,
    title_ru,
    description_ru,
    title_ua,
    description_ua,
    title_cz,
    description_cz,
    url,
    genres,
    length_of_film,
    netflix_url 
)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
""", sample_movies)
cursor.execute("SELECT * FROM movies")
# print(cursor.fetchall())
conn.commit()
conn.close()
# print(len(sample_movies))
# unique_movies = set(sample_movies)
# if len(unique_movies) != len(sample_movies):
#     print("There are completely identical movie recordings!")
# else:
#     print("There are no complete duplicates of the movies.")